<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\SalesBundle\Entity\Agent;
use Rbs\Bundle\UserBundle\Entity\User;

/**
 * AgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    public function agents()
    {
        $query = $this->createQueryBuilder('c');
        $query->join('c.user', 'u');
        $query->where('u.userType = :AGENT');
        $query->setParameter('AGENT', User::AGENT);

        return $query->getQuery()->getResult();
    }

    public function getAgentByType($agentType){
        $query = $this->createQueryBuilder('c')
            ->join('c.user', 'u')
            ->join('u.profile', 'p')
            ->where('u.deletedAt IS NULL')
            ->andWhere('u.enabled = 1')
            ->andWhere('u.userType = :AGENT')
            ->setParameter('AGENT', 'AGENT')
            ->andWhere('c.agentType = :type')
            ->setParameter('type', $agentType)
            ->orderBy('p.fullName','ASC');
        return $query->getQuery()->getResult();
    }

    public function getAgentByPhone($phone)
    {
        $query = $this->createQueryBuilder('c');
        $query->join('c.user', 'u');
        $query->join('u.profile', 'p');
        $query->where('u.userType = :AGENT');
        $query->andWhere('p.cellphone = :phone');
        $query->setParameter('AGENT', User::AGENT);
        $query->setParameter('phone', $phone);

        return $query->getQuery()->getResult();
    }

    public function getAgentListKeyValue()
    {
        $query = $this->createQueryBuilder('a');
        $query->select('a.id, a.agentID, a.chickAgentID, a.agentType, p.fullName');
        $query->join('a.user', 'u');
        $query->join('u.profile', 'p');
        $query->where('u.userType = :AGENT');
        $query->andWhere('u.enabled = 1');
        $query->andWhere('u.deletedAt IS NULL');

        $query->setParameter('AGENT', User::AGENT);
        $query->orderBy('p.fullName','ASC');

        $result = $query->getQuery()->getResult();

        $output = array();

        $output[''] = 'Select';
        foreach ($result as $agent) {
            if($agent['agentType']==Agent::AGENT_TYPE_CHICK){
                $output[$agent['id']] ='(CK) '. Agent::agentIdNameFormat($agent['chickAgentID'], $agent['fullName']);
            }else{
                $output[$agent['id']] ='(FD) '. Agent::agentIdNameFormat($agent['agentID'], $agent['fullName']);
            }
        }

        return $output;
    }

    public function getChickAgentsListByDistrict()
    {
        $query = $this->createQueryBuilder('a');
        $query->select('a.id, a.agentID, a.chickAgentID, p.fullName, z.id as zId');
        $query->join('a.user', 'u');
        $query->join('u.profile', 'p');
        $query->join('u.zilla', 'z');
        $query->where('u.userType = :AGENT');
        $query->andWhere('u.enabled = 1');
        $query->andWhere('u.deletedAt IS NULL');
        $query->andWhere('a.chickAgentID IS NOT NULL');
        $query->setParameter('AGENT', User::AGENT);
        $query->orderBy('p.fullName','ASC');

        $result = $query->getQuery()->getResult();

        $output = array();

        foreach ($result as $agent) {
            $output[$agent['zId']][] = $agent;
        }

        return $output;
    }

}
