<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgentNourishBankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentNourishBankRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    public function getAgentNourishBankByAgentCodeAndBankCode($agentCode, $bankCode)
    {
        $query = $this->createQueryBuilder('anb');
        $query->join('anb.agent', 'a');
        $query->join('anb.account', 'acc');
        $query->where('a.agentID = :code');
        $query->andWhere('acc.code = :bankcode');
        $query->setParameter('code', $agentCode );
        $query->setParameter('bankcode', $bankCode);

        return $query->getQuery()->getResult();
    }
}
