<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\SalesBundle\Entity\Agent;
use Rbs\Bundle\UserBundle\Entity\User;

/**
 * AgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    public function agents()
    {
        $query = $this->createQueryBuilder('c');
        $query->join('c.user', 'u');
        $query->where('u.userType = :AGENT');
        $query->setParameter('AGENT', User::AGENT);

        return $query->getQuery()->getResult();
    }

    public function getAgentByType($agentType){
        $query = $this->createQueryBuilder('c')
            ->join('c.user', 'u')
            ->join('u.profile', 'p')
            ->where('u.deletedAt IS NULL')
            ->andWhere('u.enabled = 1')
            ->andWhere('u.userType = :AGENT')
            ->setParameter('AGENT', 'AGENT')
            ->andWhere('c.agentType = :type')
            ->setParameter('type', $agentType)
            ->orderBy('p.fullName','ASC');
        return $query->getQuery()->getResult();
    }

    public function getAgentByPhone($phone)
    {
        $query = $this->createQueryBuilder('c');
        $query->join('c.user', 'u');
        $query->join('u.profile', 'p');
        $query->where('u.userType = :AGENT');
        $query->andWhere('p.cellphone = :phone');
        $query->setParameter('AGENT', User::AGENT);
        $query->setParameter('phone', $phone);

        return $query->getQuery()->getResult();
    }

    public function getAgentListKeyValue()
    {
        $query = $this->createQueryBuilder('a');
        $query->select('a.id, a.agentID, a.chickAgentID, a.agentType, p.fullName');
        $query->join('a.user', 'u');
        $query->join('u.profile', 'p');
        $query->where('u.userType = :AGENT');
        $query->andWhere('u.enabled = 1');
        $query->andWhere('u.deletedAt IS NULL');

        $query->setParameter('AGENT', User::AGENT);
        $query->orderBy('p.fullName','ASC');

        $result = $query->getQuery()->getResult();

        $output = array();

        $output[''] = 'Select';
        foreach ($result as $agent) {
            if($agent['agentType']==Agent::AGENT_TYPE_CHICK){
                $output[$agent['id']] ='(CK) '. Agent::agentIdNameFormat($agent['chickAgentID'], $agent['fullName']);
            }else{
                $output[$agent['id']] ='(FD) '. Agent::agentIdNameFormat($agent['agentID'], $agent['fullName']);
            }
        }

        return $output;
    }

    public function getChickAgentsListByDistrict()
    {
        $query = $this->createQueryBuilder('a');
        $query->select('a.id, a.agentID, a.chickAgentID, p.fullName, z.id as zId');
        $query->join('a.user', 'u');
        $query->join('u.profile', 'p');
        $query->join('u.zilla', 'z');
        $query->where('u.userType = :AGENT');
        $query->andWhere('u.enabled = 1');
        $query->andWhere('u.deletedAt IS NULL');
        $query->andWhere('a.chickAgentID IS NOT NULL');
        $query->setParameter('AGENT', User::AGENT);
        $query->orderBy('p.fullName','ASC');

        $result = $query->getQuery()->getResult();

        $output = array();

        foreach ($result as $agent) {
            $output[$agent['zId']][] = $agent;
        }

        return $output;
    }

    public function getChickAgentsListByDepotAreas($areas)
    {
        $query = $this->createQueryBuilder('a');
        $query->select('a.id, a.agentID, a.chickAgentID, p.fullName, z.id as zId');
        $query->join('a.user', 'u');
        $query->join('u.profile', 'p');
        $query->join('u.zilla', 'z');
        $query->where('u.userType = :AGENT');
        $query->andWhere('u.enabled = 1');
        $query->andWhere('u.deletedAt IS NULL');
        $query->andWhere('a.chickAgentID IS NOT NULL');
        $query->setParameter('AGENT', User::AGENT);
        $query->andWhere('z.id IN (:zId)');
        $query->setParameter('zId', $areas);
        $query->orderBy('p.fullName','ASC');

        $result = $query->getQuery()->getResult();

        $output = array();

        foreach ($result as $agent) {
            $output[$agent['zId']][] = $agent;
        }

        return $output;
    }



    public function getAgents($last7Days=false){
        $date = date('Y-m-d', strtotime("-4 days"));
        $today = date('Y-m-d');

        $query = $this->createQueryBuilder('a')
            ->select('a.id','a.agentCodeForDatatable','a.agentType','a.createdAt','a.updatedAt')
            ->addSelect('p.cellphoneForMapping','p.fullName','p.address')
            ->addSelect('u.email')
            ->addSelect('zilla.id as districtId','zilla.name as districtName')
            ->addSelect('upozilla.id as upozillaId','upozilla.name as upozillaName')
            ->join('a.user', 'u')
            ->join('u.profile', 'p')
            ->join('u.zilla','zilla')
            ->join('u.upozilla','upozilla')
            ->where('u.deletedAt IS NULL')
            ->andWhere('a.deletedAt IS NULL')
            ->andWhere('u.enabled = 1')
            ->andWhere('u.userType = :AGENT')
            ->setParameter('AGENT', 'AGENT');
        if($last7Days){
            $query->andWhere('a.updatedAt BETWEEN :p7days AND :today')
                ->setParameter('today', $today." 23:59:59")
                ->setParameter('p7days', $date." 00:00:00");
        }

            $query->orderBy('a.agentCodeForDatatable','ASC');
        $results= $query->getQuery()->getArrayResult();
        $returnArray=array();
        if($results){
            foreach ($results as $result) {
                $returnArray[]=array(
                    'name'=>$result['fullName'],
                    'mobile'=>$result['cellphoneForMapping'],
                    'agentId'=>$result['agentCodeForDatatable'],
                    'agentType'=>$result['agentType'],
                    'address'=>$result['address'],
                    'email'=>$result['email'],
                    'districtId'=>$result['districtId'],
                    'districtName'=>$result['districtName'],
                    'upozilaId'=>$result['upozillaId'],
                    'upozillaName'=>$result['upozillaName'],
                    'oldId'=>$result['id'],
                    'cratedAt'=>$result['createdAt']->format('Y-m-d H:i:s'),
                    'updatedAt'=>$result['updatedAt']->format('Y-m-d H:i:s'),
                );
            }
        }

        return $returnArray;
    }

    public function getAgentByCode($code, $agentType)
    {
        $query = $this->createQueryBuilder('a');
        $query->join('a.user', 'u');
        $query->join('u.profile', 'p');
        $query->where('u.userType = :AGENT');
        $query->andWhere('a.agentCodeForDatatable = :code');
        $query->andWhere('a.agentType =:agentType');
        $query->andWhere('u.enabled = 1');
        $query->andWhere('u.deletedAt IS NULL');
        $query->setParameter('AGENT', User::AGENT);
        $query->setParameter('code', $code);
        $query->setParameter('agentType', $agentType);

        return $query->getQuery()->getOneOrNullResult();
    }

}
