<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CashDepositRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CashDepositRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    public function getLastCashDepositId($user)
    {
        $query = $this->createQueryBuilder('cd');
        $query->join('cd.depo', 'd');
        $query->join('d.users', 'u');
        $query->select('cd.id');
        $query->andWhere('u.id = :user');
        $query->setParameter('user', $user);
        $query->orderBy('cd.createdAt', 'desc');
        $query->getMaxResults(1);

        return $query->getQuery()->getResult();
    }

    public function lastTotalDepositAmount($cashDepositedId)
    {
        $query = $this->createQueryBuilder('cd');
        $query->select('cd.totalDepositedAmount');
        $query->andWhere('cd.id = :cashDepositedId');
        $query->setParameter('cashDepositedId', $cashDepositedId);

        return $query->getQuery()->getResult();
    }
}
