<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CashReceiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CashReceiveRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }
}
