<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    public function customers()
    {
        $query = $this->createQueryBuilder('c');
        $query->join('c.user', 'u');
        $query->where('c.status = 1');
        $query->andWhere('u.userType = :Customer');
        $query->setParameter('Customer', 'Customer');

        return $query->getQuery()->getResult();
    }
}
