<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\SalesBundle\Entity\Customer;
use Rbs\Bundle\SalesBundle\Entity\Order;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    public function customers()
    {
        $query = $this->createQueryBuilder('c');
        $query->join('c.user', 'u');
        $query->where('u.userType = :Customer');
        $query->setParameter('Customer', 'Customer');

        return $query->getQuery()->getResult();
    }

    public function getCurrentBalance(Customer $customer)
    {
        try {
            $totalOrderAmount = $this->_em
                ->createQuery(
                    "SELECT SUM(o.totalAmount) FROM Rbs\Bundle\SalesBundle\Entity\Order o WHERE o.customer = :customer AND o.paymentState IN (:paymentState) GROUP BY o.customer"
                )
                ->setParameter('customer', $customer)
                ->setParameter('paymentState', array(Order::PAYMENT_STATE_PAID, Order::PAYMENT_STATE_PARTIALLY_PAID))
                ->getSingleScalarResult();
        } catch (\Exception $e) {
            $totalOrderAmount = 0;
        }

        try {
            $totalPaymentAmount = $this->_em
                ->createQuery("SELECT SUM(p.amount) FROM Rbs\Bundle\SalesBundle\Entity\Payment p WHERE p.customer = :customer GROUP BY p.customer")
                ->setParameter('customer', $customer)
                ->getSingleScalarResult();
        } catch (\Exception $e) {
            $totalPaymentAmount = 0;
        }

        return $totalPaymentAmount - $totalOrderAmount;
    }

    public function getCurrentCreditLimit(Customer $customer)
    {
        $customerCurrentBalance = $this->getCurrentBalance($customer);

        return $customerCurrentBalance + ($customer->getCreditLimit() + $customer->getOpeningBalance());
    }
}
