<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\CoreBundle\Entity\Depo;
use Rbs\Bundle\CoreBundle\Entity\Item;
use Rbs\Bundle\CoreBundle\Entity\ItemType;
use Rbs\Bundle\SalesBundle\Entity\Agent;
use Rbs\Bundle\SalesBundle\Entity\ChickenSetForAgent;
use Rbs\Bundle\SalesBundle\Entity\DailyDepotStock;
use Rbs\Bundle\SalesBundle\Entity\Delivery;
use Rbs\Bundle\SalesBundle\Entity\DeliveryItem;
use Rbs\Bundle\SalesBundle\Entity\Order;
use Rbs\Bundle\SalesBundle\Entity\OrderItem;
use Rbs\Bundle\SalesBundle\Entity\Stock;
use Rbs\Bundle\SalesBundle\Entity\StockHistory;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Form;

/**
 * DailyDepotStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailyDepotStockRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }


    protected function handleSearchByDepo($depo, $query)
    {
        if (!empty($depo)) {
            $query->andWhere('s.depo = :depo');
            $query->setParameter('depo', $depo);
        }
    }

    protected function handleSearchByItem($item, $query)
    {
        if (!empty($item)) {
            $query->andWhere('s.item = :item');
            $query->setParameter('item', $item);
        }
    }

    public function getDailyStock($date){

        $qb = $this->createQueryBuilder('dds');
        $qb->select('dds.id, dds.onHand, dds.onHold, d.id as dId, i.id as iId');
        $qb->join('dds.depo', 'd');
        $qb->join('dds.item', 'i');
        $qb->where($qb->expr()->between('dds.createdAt', ':start', ':end'));
        $qb->setParameters(array('start' => $date . ' 00:00:00', 'end' => $date . ' 23:59:59'));

        $results = $qb->getQuery()->getResult();
        $arrayResult = array();

        foreach ($results as $result){
            $arrayResult[$result['dId']][$result['iId']]= $result;
            $arrayResult[$result['dId']][$result['iId']]['remainingQty']=$this->getDailyDepotStockById($result['id']);
        }
        return $arrayResult;
    }

    private function getDailyDepotStockById($id){
        $stock = $this->find($id);
        return $stock->getRemainingQuantity();
    }

    public function getDailyStockByDateAndItem($date, $item){

        $qb = $this->createQueryBuilder('dds');
        $qb->select('dds.id, dds.onHand, dds.onHold, d.id as dId, i.id as iId');
        $qb->join('dds.depo', 'd');
        $qb->join('dds.item', 'i');
        $qb->where($qb->expr()->between('dds.createdAt', ':start', ':end'));
        $qb->setParameters(array('start' => $date . ' 00:00:00', 'end' => $date . ' 23:59:59'));

        $qb->andWhere('i.id = :item');
        $qb->setParameter('item', $item);

        $results = $qb->getQuery()->getResult();
        $arrayResult = array();

        foreach ($results as $result){
            $arrayResult[$result['dId']] = $result;
        }
        return $arrayResult;
    }

    public function getDailyStockByDateItemDepot($date, $item, $depot){

        $qb = $this->createQueryBuilder('dds');
        $qb->select('dds.id, dds.onHand, dds.onHold, d.id as dId, i.id as iId, i.itemUnit as itemUnit');
        $qb->join('dds.depo', 'd');
        $qb->join('dds.item', 'i');
        $qb->where($qb->expr()->between('dds.createdAt', ':start', ':end'));
        $qb->setParameters(array('start' => $date . ' 00:00:00', 'end' => $date . ' 23:59:59'));

        $qb->andWhere('d.id = :depot');
        $qb->setParameter('depot', $depot);

        $qb->andWhere('i.id = :item');
        $qb->setParameter('item', $item);

        $results = $qb->getQuery()->getOneOrNullResult();

        return $results;
    }

    public function getDailyStockByDateDepot($date, $depot){
        $qb = $this->createQueryBuilder('dds');
        $qb->select('dds.id, dds.onHand, dds.onHold, d.id as dId, i.id as iId, i.itemUnit as itemUnit');
        $qb->join('dds.depo', 'd');
        $qb->join('dds.item', 'i');
        $qb->where($qb->expr()->between('dds.createdAt', ':start', ':end'));
        $qb->setParameters(array('start' => $date . ' 00:00:00', 'end' => $date . ' 23:59:59'));

        $qb->andWhere('d.id = :depot');
        $qb->setParameter('depot', $depot);

        $results = $qb->getQuery()->getArrayResult();
        $returnArray = array();

        foreach ($results as $result){

            $dailyDepotStockObj = $this->_em->getRepository('RbsSalesBundle:DailyDepotStock')->find($result['id']);
            $receivedQty = $dailyDepotStockObj?$dailyDepotStockObj->getTotalReceivedQuantity():0;
            $transferQty = $dailyDepotStockObj?$dailyDepotStockObj->getTotalTransferredQuantity():0;


            $returnArray['stock'][$result['iId']]=$result;
            $returnArray['received'][$result['iId']]=$receivedQty;
            $returnArray['transfer'][$result['iId']]=$transferQty;
            $returnArray['remaining'][$result['iId']]=($result['onHand']+$receivedQty) - ($result['onHold']+$transferQty);
        }

        return $returnArray;
    }


    public function addStockToOnHold($date, Order $order, Depo $depo, $prevOrderItems)
    {
        if (!$depo) $depo = $order->getDepo();

        /** @var OrderItem $orderItem */
        foreach ($order->getOrderItems() as $key=>$orderItem) {

            $preQty = isset($prevOrderItems[$key])?$prevOrderItems[$key]:0;

            /** @var DailyDepotStock $stock */
            $stock = $this->getDailyStockByDateItemDepot($date, $orderItem->getItem(), $depo);
            if($stock){
                $dailyDepotStock = $this->find($stock['id']);
                $dailyDepotStock->setOnHold($dailyDepotStock->getOnHold() + $orderItem->getQuantity()-$preQty);
                $this->_em->persist($dailyDepotStock);
                $this->_em->flush();
            }
        }
    }

}