<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\SalesBundle\Entity\Delivery;
use Rbs\Bundle\SalesBundle\Entity\Order;

/**
 * DeliveryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryRepository extends EntityRepository
{
    public function prepareDeliveryOnVerifyOrder(Order $order)
    {
        $delivery = $this->findOneBy(array('order' => $order));
        if (!$delivery) {
            $delivery = new Delivery();
            $delivery->setOrder($order);
            $delivery->setWarehouse($order->getCustomer()->getWarehouse());
            $this->_em->persist($delivery);
            $this->_em->flush();
        }
    }
}
