<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\SalesBundle\Entity\Agent;
use Rbs\Bundle\SalesBundle\Entity\Delivery;
use Rbs\Bundle\SalesBundle\Entity\DeliveryItem;
use Rbs\Bundle\SalesBundle\Entity\Order;

/**
 * DeliveryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryItemRepository extends EntityRepository
{
    public function getPartialDeliveredItems(Delivery $delivery)
    {
        $orders = $delivery->getOrders();
        $data = array();
        foreach ($orders as $order) {
            $query = $this->createQueryBuilder('deliveryItem');
            $query->join('deliveryItem.orderItem', 'orderItem');
            $query->join('orderItem.item', 'item');
            $query->select('SUM(deliveryItem.qty) AS delivered, orderItem.quantity, item.name AS itemName, orderItem.id');
            $query->groupBy('deliveryItem.orderItem');
//            $query->having('orderItem.quantity >= delivered');
            $query->where("deliveryItem.order = :order")->setParameter('order', $order);
            $result = $query->getQuery()->getResult();
            foreach ($result as $row) {
                $row['orderId'] = $order->getId();
                $data[$row['orderId']][$row['id']] = $row;
            }
        }
        return $data;
    }

    public function getDeliveredItemId(Delivery $delivery)
    {
        $deliveryItems = $delivery->getDeliveryItems();
        $data = array();
        /** @var DeliveryItem $deliveryItem */
        foreach ($deliveryItems as $deliveryItem) {
            $data[$delivery->getId()][$deliveryItem->getOrder()->getId()][$deliveryItem->getOrderItem()->getId()]= $deliveryItem->getId();
        }
        return $data;
    }

    public function getTotalDeliveryItemByOrder(Order $order)
    {
        $query = $this->createQueryBuilder('d');
        $query
            ->select('SUM(d.qty) AS totalQuantity')
            ->where('d.order = :order')
            ->setParameter('order', $order);

        return $query->getQuery()->getSingleScalarResult();
    }

    public function getDeliveredItems(Order $order)
    {
        $query = $this->createQueryBuilder('di');
        $query->join('di.delivery', 'd');
        $query->join('di.orderItem', 'oi');
        $query->join('oi.item', 'i');
        $query->select('i.id');
        $query->addSelect('i.name');
        $query->addSelect('SUM(di.qty) AS totalDeliveredQuantity');
        $query->where('di.order = :order');
        $query->setParameter('order', $order->getId());
        $query->groupBy('di.orderItem');
        $query->orderBy('di.orderItem', 'ASC');

        return $query->getQuery()->getResult();
    }

    public function getDeliveredItemsByDepo($data)
    {

        $results= array();
        if(!empty($data['depo'])) {
            $query = $this->createQueryBuilder('di');
            $query->join('di.delivery', 'd');
            $query->join('d.depo', 'depo');
            $query->join('di.orderItem', 'oi');
            $query->join('oi.item', 'i');
            $query->join('i.category', 'c');
            $query->select('i.id');
            $query->addSelect('i.name as itemName');
            $query->addSelect('i.sku as itemCode');
            $query->addSelect('depo.name as depoName');
            $query->addSelect('c.id as catId');
            $query->addSelect('c.name as catName');
            $query->addSelect('SUM(di.qty) AS totalDeliveredQuantity');
            $query->where('d.shipped = 1');
            if (!empty($data['depo'])) {
                $this->handleSearchByDepo($data['depo'], $query);
            }
            $this->handleSearchByDate($query, $data['start_date']);
            $query->groupBy('i.id');
            $query->addGroupBy('d.depo');
            $query->orderBy('c.id', 'ASC');

            foreach ($query->getQuery()->getResult() as $result) {
                $results[$result['catName']][] = $result;
            }
            return $results;
        }else{
           return array();
        }
    }

    public function getChickDeliveredItemsByDepo($data)
    {

        $results= array();
        if(!empty($data['depo'])) {
            $query = $this->createQueryBuilder('di');
            $query->join('di.delivery', 'd');
            $query->join('d.depo', 'depo');
            $query->join('di.orderItem', 'oi');
            $query->join('di.order', 'o');
            $query->join('o.agent', 'a');
            $query->join('a.user', 'u');
            $query->join('u.profile', 'p');
            $query->join('u.zilla', 'z');
            $query->join('oi.item', 'i');
            $query->join('i.category', 'c');
            $query->select('i.id');
            $query->addSelect('i.name as itemName');
            $query->addSelect('i.sku as itemCode');
            $query->addSelect('depo.name as depoName');
            $query->addSelect('c.id as catId');
            $query->addSelect('c.name as catName');
            $query->addSelect('d.transportGiven');
            $query->addSelect('di.qty as totalDeliveredQuantity');
            $query->addSelect('oi.damageQuantity');
            $query->addSelect('oi.bonusQuantity');
            $query->addSelect('oi.price');
            $query->addSelect('p.fullName');
            $query->addSelect('z.name as zillaName');
            $query->addSelect('a.agentCodeForDatatable');
            $query->where('d.shipped = 1');
            $query->andWhere('o.orderType = :type');
            $query->setParameter('type', Order::ORDER_TYPE_CHICK);
            if (!empty($data['depo'])) {
                $this->handleSearchByDepo($data['depo'], $query);
            }
            $this->handleSearchByDate($query, $data['start_date']);
//            $query->groupBy('i.id');
//            $query->addGroupBy('d.depo');
//            $query->orderBy('c.id', 'ASC');

            foreach ($query->getQuery()->getResult() as $result) {
                $results[$result['catName']][] = $result;
            }
            return $results;
        }else{
           return array();
        }
    }

    public function getDeliveryIncentive($deliveryId)
    {
        $query = $this->createQueryBuilder('di');
        $query->join('di.delivery', 'd');
        $query->join('di.order', 'o');
        $query->join('o.agent', 'a');
        $query->join('di.orderItem', 'oi');
        $query->join('oi.item', 'i');
        $query->join('i.itemType', 'it');
        $query->join('d.depo', 'depo');
        $query->select('di.qty as quantity');
        $query->addSelect('a.id as agentId');
        $query->addSelect('it.id as itemTypeId');
        $query->addSelect('depo.id as depoId');
        $query->addSelect('it.itemType as itemType');
        $query->where('d.id = :deliveryId');
        $query->setParameters(array('deliveryId'=>$deliveryId));

        return $query->getQuery()->getResult();
    }

    protected function handleSearchByDepo($depo, $query)
    {
        if (!empty($depo)) {
            $query->andWhere('d.depo = :depo');
            $query->setParameter('depo', $depo);
        }
    }
    protected function handleSearchByDate($query, $startDate)
    {
        if (!empty($startDate)) {
            $startDate = date('Y-m-d', strtotime($startDate));
            $query->andWhere('d.createdAt >= :startDate');
            $query->andWhere('d.createdAt <= :endDate');
            $query->setParameter('startDate', $startDate.' 00:00:00');
            $query->setParameter('endDate', $startDate.' 23:59:59');
        }
    }
}
