<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use DateTime;
use Doctrine\Common\Util\Debug;
use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\CoreBundle\Entity\Depo;
use Rbs\Bundle\SalesBundle\Entity\Delivery;
use Rbs\Bundle\SalesBundle\Entity\DeliveryItem;
use Rbs\Bundle\SalesBundle\Entity\Order;

/**
 * DeliveryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryRepository extends EntityRepository
{
    public function createDelivery($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }
    
    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }
  
    public function create(Order $order, Depo $depo, $request)
    {
        $delivery = new Delivery();
        $delivery->setDepo($depo);
        $this->_em->persist($delivery);
        $this->_em->flush();
        
        return $delivery;
    }

    public function savePartial($delivery, $data)
    {
        $output = array('orders' => array());
        foreach ($data['qty'] as $itemId => $qty) {
            $item = $this->_em->getRepository('RbsSalesBundle:OrderItem')->find($itemId);

            $deliveryItem = new DeliveryItem();
            $deliveryItem->setOrder($item->getOrder());
            $deliveryItem->setDelivery($delivery);
            $deliveryItem->setOrderItem($item);
            $deliveryItem->setQty($qty);
            $this->_em->persist($deliveryItem);

            $output['orders'][$item->getOrder()->getId()] = $item->getOrder()->getId();
        }

        $this->_em->flush();

        return $output;
    }

    public function save($delivery, $data)
    {
        $delivery->setShipped(true);
        $output = array('orders' => array());
        foreach ($data['qty'] as $orderId => $deliveryItems) {
            foreach ($deliveryItems as $itemId => $qty) {
                $order = $this->_em->getRepository('RbsSalesBundle:Order')->find($orderId);
                $item = $this->_em->getRepository('RbsSalesBundle:OrderItem')->find($itemId);
                $amount = $this->_em->getRepository('RbsCoreBundle:TransportIncentive')->getTransportIncentive($order->getAgent()->getUser()->getUpozilla()->getId(), $order->getDepo()->getId(), $item->getItem()->getItemType()->getId());

                if($amount){
                    $amount = $amount[0]['amount'];
                }else{
                    $amount = 0;
                }

                $deliveryItem = new DeliveryItem();
                $deliveryItem->setOrder($order);
                $deliveryItem->setDelivery($delivery);
                $deliveryItem->setOrderItem($item);
                $deliveryItem->setQty($qty);
                $deliveryItem->setTransportIncentiveAmount($qty*$amount);

                $this->_em->persist($deliveryItem);

                $output['orders'][$order->getId()] = $order;
            }
        }

        if (!empty($data['checked-items'])) {
            $previousItems = $data['previous-items'];
            foreach ($data['checked-items'] as $orderId => $deliveryItems) {
                foreach ($deliveryItems as $itemId => $qty) {

                    if (!array_key_exists($itemId, $previousItems[$orderId])) {
                        continue;
                    }

                    $order = $this->_em->getRepository('RbsSalesBundle:Order')->find($orderId);
                    $item = $this->_em->getRepository('RbsSalesBundle:OrderItem')->find($itemId);

                    $deliveryItem = new DeliveryItem();
                    $deliveryItem->setOrder($order);
                    $deliveryItem->setDelivery($delivery);
                    $deliveryItem->setOrderItem($item);
                    $deliveryItem->setQty($previousItems[$orderId][$itemId]);

                    $this->_em->persist($deliveryItem);

                    $output['orders'][$order->getId()] = $order;
                }
            }
        }

        $this->_em->flush();

        return $output;
    }

    public function deliveryUpdate( $data)
    {
        $output = array('orders' => array());
        foreach ($data as $deliveryId => $deliveryItems) {
            foreach ($deliveryItems as $deliveryItemId => $qty) {
                $deliveryItem = $this->_em->getRepository('RbsSalesBundle:DeliveryItem')->find($deliveryItemId);
                $amount = $this->_em->getRepository('RbsCoreBundle:TransportIncentive')->getTransportIncentive($deliveryItem->getOrder()->getAgent()->getUser()->getUpozilla()->getId(), $deliveryItem->getOrder()->getDepo()->getId(), $deliveryItem->getOrderItem()->getItem()->getItemType()->getId());

                if($amount){
                    $amount = $amount[0]['amount'];
                }else{
                    $amount = 0;
                }
                $deliveryItem->setQty($qty);
                $deliveryItem->setTransportIncentiveAmount($qty*$amount);

                $this->_em->persist($deliveryItem);

                $output['orders'][$deliveryItem->getOrder()->getId()] = $deliveryItem->getOrder();
            }
        }

        $this->_em->flush();

        return $output;
    }

    public function saveForChick($delivery, $data)
    {
        $delivery->setShipped(true);
        $output = array('orders' => array());
        foreach ($data['qty'] as $orderId => $deliveryItems) {
            foreach ($deliveryItems as $itemId => $qty) {
                $order = $this->_em->getRepository('RbsSalesBundle:Order')->find($orderId);
                $item = $this->_em->getRepository('RbsSalesBundle:OrderItem')->find($itemId);

                $item->setBonusQuantity($item->calculateBonusQuantity());
                $item->setDamageQuantity($data['damage-qty'][$orderId][$itemId]);

                $this->_em->persist($item);

//                $qty = $qty - $data['damage-qty'][$orderId][$itemId];

                $checkDuplicateDeliveryItem = $this->_em->getRepository('RbsSalesBundle:DeliveryItem')->findOneBy(array('delivery'=>$delivery,'orderItem'=>$item));
                if(!$checkDuplicateDeliveryItem){
                    $deliveryItem = new DeliveryItem();
                    $amount = $this->_em->getRepository('RbsCoreBundle:TransportIncentive')->getTransportIncentive($order->getAgent()->getUser()->getUpozilla()->getId(), $order->getDepo()->getId(), $item->getItem()->getItemType()->getId());

                    if($amount){
                        $amount = $amount[0]['amount'];
                    }else{
                        $amount = 0;
                    }

                    $deliveryItem->setTransportIncentiveAmount($qty*$amount);

                    $deliveryItem->setOrder($order);
                    $deliveryItem->setDelivery($delivery);
                    $deliveryItem->setOrderItem($item);
                    $deliveryItem->setQty($qty);

                    $this->_em->persist($deliveryItem);
                }

                $output['orders'][$order->getId()] = $order;
            }
        }

        if (!empty($data['checked-items'])) {
            $previousItems = $data['previous-items'];
            foreach ($data['checked-items'] as $orderId => $deliveryItems) {
                foreach ($deliveryItems as $itemId => $qty) {

                    if (!array_key_exists($itemId, $previousItems[$orderId])) {
                        continue;
                    }

                    $order = $this->_em->getRepository('RbsSalesBundle:Order')->find($orderId);
                    $item = $this->_em->getRepository('RbsSalesBundle:OrderItem')->find($itemId);


                    $checkDuplicateDeliveryItem = $this->_em->getRepository('RbsSalesBundle:DeliveryItem')->findOneBy(array('delivery'=>$delivery,'orderItem'=>$item));
                    if(!$checkDuplicateDeliveryItem) {
                        $deliveryItem = new DeliveryItem();
                        $deliveryItem->setOrder($order);
                        $deliveryItem->setDelivery($delivery);
                        $deliveryItem->setOrderItem($item);
                        $deliveryItem->setQty($previousItems[$orderId][$itemId]);

                        $this->_em->persist($deliveryItem);
                    }
                    $output['orders'][$order->getId()] = $order;
                }
            }
        }

        $this->_em->flush();

        return $output;
    }

    public function updateForChick($delivery, $data)
    {
        $delivery->setShipped(true);
        $output = array('orders' => array());
        foreach ($data['qty'] as $orderId => $deliveryItems) {
            foreach ($deliveryItems as $itemId => $qty) {
                $order = $this->_em->getRepository('RbsSalesBundle:Order')->find($orderId);
                $item = $this->_em->getRepository('RbsSalesBundle:OrderItem')->find($itemId);
                $item->setQuantity($qty);
                $item->setBonusQuantity($item->calculateBonusQuantity());
                $item->setDamageQuantity($data['damage-qty'][$orderId][$itemId]);

                $this->_em->persist($item);

//                $qty = $qty - $data['damage-qty'][$orderId][$itemId];

                $deliveryItem = $this->_em->getRepository('RbsSalesBundle:DeliveryItem')->find($data['deliveryItemId'][$orderId][$itemId]);

                $amount = $this->_em->getRepository('RbsCoreBundle:TransportIncentive')->getTransportIncentive($order->getAgent()->getUser()->getUpozilla()->getId(), $order->getDepo()->getId(), $item->getItem()->getItemType()->getId());

                if($amount){
                    $amount = $amount[0]['amount'];
                }else{
                    $amount = 0;
                }

                $deliveryItem->setTransportIncentiveAmount($qty*$amount);

                $deliveryItem->setOrder($order);
                $deliveryItem->setDelivery($delivery);
                $deliveryItem->setOrderItem($item);
                $deliveryItem->setQty($qty);

                $this->_em->persist($deliveryItem);

                $output['orders'][$order->getId()] = $order;
            }
        }


        $this->_em->flush();

        return $output;
    }

    public function getDeliveriesForTransportIncentive($firstDateOfPreviousMonth, $lastDateOfPreviousMonth)
    {
        $query = $this->createQueryBuilder('d');
        $query->join('d.orders', 'o');
        $query->select('d.id');
        $query->where('d.createdAt >= :startDate');
        $query->andWhere('d.createdAt <= :endDate');
        $query->andWhere('o.deliveryState = :SHIPPED OR o.deliveryState = :PARTIALLY_SHIPPED');
        $query->setParameters(array('startDate'=>$firstDateOfPreviousMonth, 'endDate'=>$lastDateOfPreviousMonth, 'SHIPPED'=>Order::DELIVERY_STATE_SHIPPED, 'PARTIALLY_SHIPPED'=>Order::DELIVERY_STATE_PARTIALLY_SHIPPED));

        return $query->getQuery()->getResult();
    }


    public function getDeliveryQuantityByZoneWiseForApi($date){

        $qp = $this->createQueryBuilder('d');
        $qp->join('d.deliveryItems', 'di');
        $qp->join('di.order', 'o');
        $qp->join('di.orderItem', 'oi');
        $qp->join('o.agent', 'a');
        $qp->join('a.user', 'u');
        $qp->join('u.zilla', 'z');
        $qp->join('oi.item', 'i');
        $qp->select('d.id');
        $qp->addSelect('i.id AS iId');
        $qp->addSelect('i.name AS iName');
        $qp->addSelect('z.id AS districtId');
        $qp->addSelect('z.name AS districtName');
        $qp->addSelect('z.parentId AS regionId');
        $qp->addSelect('SUM(di.qty) AS totalQuantity');
        $qp->where('o.orderType = :orderType');
        $qp->setParameter('orderType', Order::ORDER_TYPE_FEED);
        $qp->andWhere('o.deliveryState IN (:deliveryState)');
        $qp->setParameter('deliveryState', ['PARTIALLY_SHIPPED','SHIPPED']);

        $startDate = $date?date('Y-m-d', strtotime($date)):date('Y-m-d', strtotime("now"));
        $endDate = $date?date('Y-m-d', strtotime($date)):date('Y-m-d', strtotime("now"));
        $qp->andWhere('d.createdAt >= :startDate');
        $qp->andWhere('d.createdAt <= :endDate');
        $qp->setParameter('startDate', $startDate.' 00:00:00');
        $qp->setParameter('endDate', $endDate.' 23:59:59');

        $qp->groupBy('z.id');
        $qp->addGroupBy('i.id');
        $qp->orderBy('z.name', 'ASC');
        $results=$qp->getQuery()->getResult();
        $returnArray= array();
        if($results){
            foreach ($results as $result) {
                $returnArray[] = array(
                    'itemId'=>$result['iId'],
                    'itemName'=>$result['iName'],
                    'districtId'=>$result['districtId'],
                    'districtName'=>$result['districtName'],
                    'regionId'=>$result['regionId'],
                    'totalQuantity'=>$result['totalQuantity'],
                );
            }
        }

        return $returnArray;

    }
}