<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\CoreBundle\Entity\Location;
use Rbs\Bundle\SalesBundle\Entity\Incentive;
use Rbs\Bundle\SalesBundle\Entity\Order;
use Rbs\Bundle\SalesBundle\Entity\OrderItem;
use Rbs\Bundle\SalesBundle\Entity\Payment;
use Rbs\Bundle\SalesBundle\Entity\Sms;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create(Order $order)
    {
        $this->calculateOrderAmount($order);
        $order->setTotalApprovedAmount($order->getItemsTotalAmount());
        $this->setStatus($order);
        $this->setSms($order);

        $this->_em->persist($order);
        $this->_em->flush();
    }

    public function createWithoutSms(Order $order)
    {
        $this->calculateOrderAmount($order);
        $this->orderPayment($order);
        $order->setTotalApprovedAmount($order->getItemsTotalAmount());
        $order->setPaidAmount($order->getTotalPaymentDepositedAmount());
//        $this->setAllPendingStatus($order);
        $this->setStatus($order);
        $order->setOrderVia('ONLINE');
//        $this->setSms($order)
        $this->_em->persist($order);
        $this->_em->flush();
    }

    public function update(Order $order, $resetStatus = false)
    {
        $this->calculateOrderAmount($order);
        $this->setSms($order);
        if ($resetStatus) {
            $this->setStatus($order);
        }

        $this->_em->flush();
        return $this->_em;
    }
    public function onlyUpdate(Order $order)
    {
        $this->calculateOrderAmount($order);
        $this->_em->persist($order);
        $this->_em->flush();
        return $this->_em;
    }
    public function updatePartialShippedStatus(Order $order)
    {
        $this->_em->persist($order);
        $this->_em->flush();
        return $this->_em;
    }

    public function updateWithoutSms(Order $order, $resetStatus = false)
    {

        $this->calculateOrderAmount($order);
        $this->orderPayment($order);
        if($order->getPaidAmount()!=$order->getTotalPaymentDepositedAmount()){
            $order->setPaidAmount($order->getTotalPaymentDepositedAmount());
            $order->setPaymentState(Order::PAYMENT_STATE_PENDING);
        }

        /*if ($order->getTotalAmount() <= $order->getPaidAmount()) {
            $order->setPaymentState(Order::PAYMENT_STATE_PAID);
        } else {
            $order->setPaymentState(Order::PAYMENT_STATE_PARTIALLY_PAID);
        }*/
        $this->_em->persist($order);
        $this->_em->flush();
        return $this->_em;
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function calculateOrderAmount(Order $order)
    {
        /** @var OrderItem $orderItems */
        foreach ($order->getOrderItems() as $orderItems) {
            $orderItems->setOrder($order);
            $orderItems->calculateTotalAmount(true);
        }
        $order->setTotalAmount($order->getItemsTotalAmount());
    }

    public function orderPayment(Order $order)
    {
        $agent = $order->getAgent();
        if($order->getPayments()[0]){
            /** @var Payment $payment */
            foreach ($order->getPayments() as $payment) {
                if($payment){
                    $payment->setAgent($agent);
                    if($payment->isVerified()==true){
                        $payment->setAmount($payment->getDepositedAmount());
                    }else{
                        $payment->setAmount(0);
                    }
                    $payment->setTransactionType(Payment::CR);
//                    $this->_em->getRepository('RbsSalesBundle:Order')->orderAmountAdjust($payment);
                    $payment->addOrder($order);
                }
//            $this->_em->persist($payment);
            }
        }

    }

    /**
     * @param Order $order
     */
    protected function setStatus(Order $order)
    {
        $order->setOrderState('PROCESSING');
        $order->setPaymentState('PENDING');
        $order->setDeliveryState('PENDING');
    }

    /**
     * @param Order $order
     */
    protected function setAllPendingStatus(Order $order)
    {
        $order->setOrderState('PENDING');
        $order->setPaymentState('PENDING');
        $order->setDeliveryState('PENDING');
    }

    protected function setSms(Order $order)
    {
        if ($order->getRefSMS()) {
            $order->getRefSMS()->setStatus('READ');
            $order->getRefSMS()->setOrder($order);
        }
    }

    function getAgentWiseOrder($agent, $returnQuery = false)
    {
        $query = $this->createQueryBuilder('o')
            ->where('o.deletedBy IS NULL')
            ->orderBy('o.id', 'DESC')
            ->andWhere('o.orderState != :complete or o.orderState != :cancel')
            ->andWhere('o.paymentState != :paid')
            ->andWhere('o.agent = :agent')
            ->setParameter('agent', $agent)
            ->setParameter('complete', Order::ORDER_STATE_COMPLETE)
            ->setParameter('cancel', Order::ORDER_STATE_CANCEL)
            ->setParameter('paid', Order::PAYMENT_STATE_PAID);

        if ($returnQuery) {
            return $query;
        }

        return $query->getQuery()->getResult();
    }

    public function adjustPaymentViaSms($payments)
    {
        /** @var Payment $payment */
        foreach ($payments as $payment) {
            if ($payment->getPaymentVia() == 'SMS') {
                $this->orderAmountAdjust($payment);
            }
        }
    }

    public function orderAmountAdjust($payments)
    {
        /** @var Payment $payments */
        $amount = $payments->getAmount();

        /** @var Order $order */
        foreach($payments->getOrders() as $order){
            $dueAmount = $order->getDueAmount();
            if($amount != 0 and $dueAmount != 0){
                if ($amount >= $dueAmount) {
                    $amount = $amount - $dueAmount;
                    $order->setPaidAmount($order->getPaidAmount() + $dueAmount);
                    $order->setPaymentState(Order::PAYMENT_STATE_PAID);

                    $this->_em->getRepository('RbsSalesBundle:OrderItem')->orderAmountAdjust($order);
                } else{
                    $order->setPaidAmount($order->getPaidAmount() + $amount);
                    $order->setPaymentState(Order::PAYMENT_STATE_PARTIALLY_PAID);
                    $amount = 0;

                    $this->_em->getRepository('RbsSalesBundle:OrderItem')->orderAmountAdjust($order);
                }
            }
            $this->update($order);
        }
    }

    public function updateDeliveryState($orders, $forChick=false)
    {
        $orderItemRepo = $this->_em->getRepository('RbsSalesBundle:OrderItem');
        $deliveryItemRepo = $this->_em->getRepository('RbsSalesBundle:DeliveryItem');

        /** @var Order $order */
        foreach ($orders as $order) {

            if ((int)$deliveryItemRepo->getTotalDeliveryItemByOrder($order) < (int)$orderItemRepo->getTotalOrderItemByOrder($order)) {
                $order->setDeliveryState(Order::DELIVERY_STATE_PARTIALLY_SHIPPED);
                if($forChick){
                    $order->setVehicleState(Order::VEHICLE_STATE_PARTIALLY_SHIPPED);
                }
            } else {
                $order->setDeliveryState(Order::DELIVERY_STATE_SHIPPED);
                if($forChick){
                    $order->setVehicleState(Order::VEHICLE_STATE_OUT);
                }
            }
            $order->setOrderState(Order::ORDER_STATE_COMPLETE);
            $this->_em->persist($order);
            $this->_em->flush();
        }
    }

    public function updateDeliveryStatePartialShipped($orders)
    {
        $orderItemRepo = $this->_em->getRepository('RbsSalesBundle:OrderItem');
        $deliveryItemRepo = $this->_em->getRepository('RbsSalesBundle:DeliveryItem');
        /** @var Order $order */
        foreach ($orders as $orderId) {
            $order = $this->_em->getRepository('RbsSalesBundle:Order')->find($orderId);
            if ((int)$deliveryItemRepo->getTotalDeliveryItemByOrder($order) < (int)$orderItemRepo->getTotalOrderItemByOrder($order)) {
                $order->setDeliveryState(Order::DELIVERY_STATE_PARTIALLY_SHIPPED);
            } else {
                $order->setDeliveryState(Order::DELIVERY_STATE_SHIPPED);
            }

            $order->setOrderState(Order::ORDER_STATE_COMPLETE);
            $this->_em->persist($order);
        }

        $this->_em->flush();
    }

    public function newOrderBySms(Sms $sms)
    {


    }

    public function cancelOrder(Order $order)
    {
        if ($order->getOrderState() != Order::ORDER_STATE_PENDING) {
            $stockRepo = $this->_em->getRepository('RbsSalesBundle:Stock');
            $oldQty = $stockRepo->extractOrderItemQuantity($order);
            $stockRepo->subtractFromOnHold($oldQty, $order->getDepo());
        }

        $order->setOrderState(Order::ORDER_STATE_CANCEL);
        $order->setPaymentState(Order::PAYMENT_STATE_PENDING);
        $order->setDeliveryState(Order::DELIVERY_STATE_PENDING);
        $order->setPaidAmount(0);

        /** @var OrderItem $item */
        foreach ($order->getOrderItems() as $item) {
            $item->setPaidAmount(0);
            $this->_em->persist($item);
        }

        /** @var Payment $payment */
        foreach ($order->getPayments() as $payment) {
            if ($payment->getPaymentVia() == 'SMS' & !$payment->isVerified() && $payment->getTransactionType() == Payment::CR) {
                $this->_em->remove($payment);
            } else if ($payment->getTransactionType() == Payment::DR) {
                $this->_em->remove($payment);
                // Instead of delete DR payment, first though was insert another positive payment
                /*$payment = new Payment();
                $payment->setAgent($payment->getAgent());
                $payment->setAmount($payment->getAmount());
                $payment->setPaymentMethod(Payment::PAYMENT_METHOD_BANK);
                $payment->setRemark('Return due to cancel order: ' . $order->getId());
                $payment->setDepositDate(date("Y-m-d"));
                $payment->setTransactionType(Payment::CR);
                $payment->setVerified(true);
                $payment->addOrder($order);
                $this->_em->getRepository('RbsSalesBundle:Payment')->create($payment);*/
            }
        }

        $this->_em->flush();

        $this->update($order);
    }

    public function getOrdersForSalesIncentive($durationType)
    {
        $query = $this->createQueryBuilder('o');
        $query->join('o.agent', 'a');
        $query->join('o.orderIncentiveFlag', 'oif');
        $query->select('o.id as orderId');
        $query->addSelect('a.id as agentId');

        if($durationType == Incentive::YEAR){
            $query->andWhere('oif.yearFlag = false');
        }else{
            $query->andWhere('oif.monthFlag = false');
        }

        $query->andWhere('o.orderState = :COMPLETE');
        $query->setParameters(array('COMPLETE'=>Order::ORDER_STATE_COMPLETE));

        return $query->getQuery()->getResult();
    }


    public function getOrdersZoneWise($user, $agent)
    {
        $regions = $this->getEntityManager()->getRepository('RbsCoreBundle:Location')->getRegionsForChick();
        $districts = $this->getEntityManager()->getRepository('RbsCoreBundle:Location')->getDistrictsForChick();

        $orders = $this->getOrdersOption($user, $agent);
        $dataArray = array();
        /** @var  Location $region */
        foreach ($regions as $region){
            /** @var  Location $district */
            foreach ($districts as $district){
                if($district['parentId']==$region['id']){

                    if (array_key_exists($district['id'], $orders)){
                        foreach ($orders[$district['id']] as $key=>$order){
                            $dataArray[$region['name']][$key]=$order;
                        }
                    }

                }


            }
        }

        return $dataArray;


    }

    private function getOrdersOption($user, $agent){
        $qp = $this->createQueryBuilder('o');
        $qp->join('o.depo', 'd');
        $qp->join('d.users', 'u');
        $qp->join('o.location', 'l');
        $qp->where('o.deliveryState = :PARTIALLY_SHIPPED OR o.deliveryState = :READY');
        $qp->andWhere('o.orderType = :orderType');
        $qp->andWhere('u.id = :user');
        $qp->andWhere('o.vehicleState IS NULL or o.vehicleState = :vehicle');
        $qp->setParameters(array('PARTIALLY_SHIPPED'=>Order::DELIVERY_STATE_PARTIALLY_SHIPPED, 'READY'=>Order::DELIVERY_STATE_READY,
            'user' => $user->getId()));
        $qp->setParameter('orderType', Order::ORDER_TYPE_CHICK);
        $qp->setParameter('vehicle', Order::VEHICLE_STATE_PARTIALLY_SHIPPED);
        if($agent){
            $qp->andWhere('o.agent = :agent');
            $qp->setParameter('agent', $agent);
        }
        $qp->orderBy('o.id', 'desc');
        $arrayData = array();
        /** @var  Order $item */
        foreach ($qp->getQuery()->getResult() as $item){
            $arrayData[$item->getLocation()->getParentId()][$item->getId()]= $item->getOrderInfoWithAgentForChick().', Qty:'.$item->getOrderItemsTotalQuantity();
        }

        return $arrayData;
    }

    public function getDailyFeedOrder($data){

        $results= array();
        if(!empty($data['start_date'])) {
            $qp = $this->createQueryBuilder('o');
            $qp->join('o.depo', 'd');
            $qp->join('o.orderItems', 'oi');
            $qp->join('oi.item', 'i');
            $qp->join('i.category', 'c');
            $qp->select('o.id');
            $qp->addSelect('d.id as depotId');
            $qp->addSelect('c.id as catId');
            $qp->addSelect('c.name as catName');
            $qp->addSelect('d.name as depotName');
            $qp->addSelect('oi.totalAmount');
            $qp->addSelect('SUM(oi.quantity) AS totalQuantity');
            $qp->addSelect('SUM(oi.totalAmount) AS totalAmount');
            $qp->where('o.orderType = :orderType');
            $qp->setParameter('orderType', Order::ORDER_TYPE_FEED);
            if (!empty($data['depo'])) {
                $this->handleSearchByDepot($data['depo'], $qp);
            }
            $this->handleSearchByDate($qp, $data['start_date'], $data['start_date']);
            $qp->groupBy('o.depo');
            $qp->addGroupBy('c.id');
            $qp->orderBy('d.name', 'ASC');

            foreach ($qp->getQuery()->getResult() as $result) {
                $results[$result['depotId']][$result['catId']] = $result;
            }
            return $results;
        }else{
            return array();
        }


    }

    public function getDailyFeedOrderItem($data){

        $results= array();
        if(!empty($data['start_date']) && !empty($data['end_date'])) {
            $qp = $this->createQueryBuilder('o');
            $qp->join('o.depo', 'd');
            $qp->join('o.orderItems', 'oi');
            $qp->join('oi.item', 'i');
            $qp->join('i.category', 'c');
            $qp->select('o.id');
            $qp->addSelect('d.id as depotId');
            $qp->addSelect('d.name as depotName');
            $qp->addSelect('oi.totalAmount');
            $qp->addSelect('oi.price as unitPrice');
            $qp->addSelect('c.id as catId');
            $qp->addSelect('i.sku as itemCode');
            $qp->addSelect('i.name as itemName');
            $qp->addSelect('c.id as catCode');
            $qp->addSelect('c.name as catName');
            $qp->addSelect('SUM(oi.quantity) AS totalQuantity');
            $qp->addSelect('SUM(oi.totalAmount) AS totalAmount');
            $qp->where('o.orderType = :orderType');
            $qp->setParameter('orderType', Order::ORDER_TYPE_FEED);
            if (!empty($data['depo'])) {
                $this->handleSearchByDepot($data['depo'], $qp);
            }
            $this->handleSearchByDate($qp, $data['start_date'], $data['end_date']);
            $qp->groupBy('o.depo');
            $qp->addGroupBy('i.id');
            $qp->orderBy('d.name', 'ASC');
            $qp->addOrderBy('i.name', 'ASC');

            foreach ($qp->getQuery()->getResult() as $result) {
                $results[$result['depotName']][$result['catName']][] = $result;
            }
            return $results;
        }else{
            return array();
        }


    }

    protected function handleSearchByDepot($depot, $query)
    {
        if (!empty($depot)) {
            $query->andWhere('d.id = :depot');
            $query->setParameter('depot', $depot);
        }
    }

    protected function handleSearchByDate($query, $startDate, $endDate)
    {
        if (!empty($startDate)&&!empty($endDate)) {
            $startDate = date('Y-m-d', strtotime($startDate));
            $endDate = date('Y-m-d', strtotime($endDate));
            $query->andWhere('o.createdAt >= :startDate');
            $query->andWhere('o.createdAt <= :endDate');
            $query->setParameter('startDate', $startDate.' 00:00:00');
            $query->setParameter('endDate', $endDate.' 23:59:59');
        }
    }
}