<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\SalesBundle\Entity\Order;

/**
 * OrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    public function orderAmountAdjust(Order $order)
    {
        $amount = $order->getPaidAmount();

        foreach($order->getOrderItems() as $orderItem){
            $dueAmount = $orderItem->getDueAmount();

            if($amount != 0 and $dueAmount != 0){
                if ($amount >= $dueAmount) {
                    $amount = $amount - $dueAmount;
                    $orderItem->setPaidAmount($dueAmount);
                } else{
                    $orderItem->setPaidAmount($amount);
                    $amount = 0;
                }
            }else{
                $orderItem->setPaidAmount(0);
            }
            $this->update($orderItem);
        }
    }

    public function getTotalOrderItemByOrder(Order $order)
    {
        $query = $this->createQueryBuilder('o');
        $query
            ->select('SUM(o.quantity) AS totalQuantity')
            ->where('o.order = :order')
            ->setParameter('order', $order);

        return $query->getQuery()->getSingleScalarResult();
    }
}
