<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\SalesBundle\Entity\Order;
use Rbs\Bundle\SalesBundle\Entity\OrderItem;
use Rbs\Bundle\SalesBundle\Entity\Payment;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create(Order $order)
    {
        $this->calculateOrderAmount($order);
        $this->setStatus($order);
        $this->setSms($order);

        $this->_em->persist($order);
        $this->_em->flush();
    }

    public function update(Order $order, $resetStatus = false)
    {
        $this->calculateOrderAmount($order);
        $this->setSms($order);
        if ($resetStatus) {
            $this->setStatus($order);
        }

        $this->_em->flush();
        return $this->_em;
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    protected function calculateOrderAmount(Order $order)
    {
        /** @var OrderItem $orderItems */
        foreach ($order->getOrderItems() as $orderItems) {
            $orderItems->setOrder($order);
            $orderItems->calculateTotalAmount(true);
        }
        $order->setTotalAmount($order->getItemsTotalAmount());
    }

    /**
     * @param Order $order
     */
    protected function setStatus(Order $order)
    {
        $order->setOrderState('PROCESSING');
        $order->setPaymentState('PENDING');
        $order->setDeliveryState('PENDING');
    }

    protected function setSms(Order $order)
    {
        if ($order->getRefSMS()) {
            $order->getRefSMS()->setStatus('READ');
            $order->getRefSMS()->setOrder($order);
        }
    }

    function getCustomerWiseOrder($customer, $returnQuery = false)
    {
        $query = $this->createQueryBuilder('o')
            ->where('o.deletedAt IS NULL')
            ->orderBy('o.id', 'DESC')
            ->andWhere('o.orderState != :complete or o.orderState != :cancel')
            ->andWhere('o.paymentState != :paid')
            ->andWhere('o.customer = :customer')
            ->setParameter('customer', $customer)
            ->setParameter('complete', Order::ORDER_STATE_COMPLETE)
            ->setParameter('cancel', Order::ORDER_STATE_CANCEL)
            ->setParameter('paid', Order::PAYMENT_STATE_PAID);

        if ($returnQuery) {
            return $query;
        }

        return $query->getQuery()->getResult();
    }

    public function orderAmountAdjust($payments)
    {
        /** @var Payment $payments */
        $amount = $payments->getAmount();

        /** @var Order $order */
        foreach($payments->getOrders() as $order){
            $dueAmount = $order->getDueAmount();
            if($amount != 0 and $dueAmount != 0){
                if ($amount >= $dueAmount) {
                    $amount = $amount - $dueAmount;
                    $order->setPaidAmount($order->getPaidAmount() + $dueAmount);
                    $order->setPaymentState(Order::PAYMENT_STATE_PAID);

                    $this->_em->getRepository('RbsSalesBundle:OrderItem')->orderAmountAdjust($order);
                } else{
                    $order->setPaidAmount($order->getPaidAmount() + $amount);
                    $order->setPaymentState(Order::PAYMENT_STATE_PARTIALLY_PAID);
                    $amount = 0;

                    $this->_em->getRepository('RbsSalesBundle:OrderItem')->orderAmountAdjust($order);
                }
            }
            $this->update($order);
        }
    }

    public function updateDeliveryState($orders)
    {
        $orderItemRepo = $this->_em->getRepository('RbsSalesBundle:OrderItem');
        $deliveryItemRepo = $this->_em->getRepository('RbsSalesBundle:DeliveryItem');

        /** @var Order $order */
        foreach ($orders as $order) {
            var_dump((int)$deliveryItemRepo->getTotalDeliveryItemByOrder($order), (int)$orderItemRepo->getTotalOrderItemByOrder($order));
            if ((int)$deliveryItemRepo->getTotalDeliveryItemByOrder($order) < (int)$orderItemRepo->getTotalOrderItemByOrder($order)) {
                $order->setDeliveryState(Order::DELIVERY_STATE_PARTIALLY_SHIPPED);
            } else {
                $order->setDeliveryState(Order::DELIVERY_STATE_SHIPPED);
            }

            $this->_em->persist($order);
        }

        $this->_em->flush();
    }
}