<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\SalesBundle\Entity\Order;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create(Order $data)
    {
        $this->_em->persist($data);
        if($data->getRefSMS()){
            $data->getRefSMS()->setOrder($data);
        }
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update(Order $data)
    {
        $this->_em->persist($data);
        if($data->getRefSMS()){
            $data->getRefSMS()->setOrder($data);
        }
        $this->_em->flush();
        return $this->_em;
    }
}
