<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\SalesBundle\Entity\OrderChickTemp;
use Rbs\Bundle\SalesBundle\Entity\OrderItemChickTemp;
/**
 * OrderChickTempRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderChickTempRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create(OrderChickTemp $order)
    {
        $this->calculateOrderAmount($order);
        $this->_em->persist($order);
        $this->_em->flush();
    }


    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function calculateOrderAmount(OrderChickTemp $order)
    {
        /** @var OrderItemChickTemp $orderItems */
        foreach ($order->getOrderItems() as $orderItems) {
            $orderItems->setOrder($order);
            $orderItems->calculateTotalAmount(true);
        }
        $order->setTotalAmount($order->getItemsTotalAmount());
    }


    public function getOrderChickTempByOrderDate($date, $depot)
    {
        $qb = $this->createQueryBuilder('oct');
        $qb->where($qb->expr()->between('oct.createdAt', ':start', ':end'));
        $qb->setParameters(array('start' => $date . ' 00:00:00', 'end' => $date . ' 23:59:59'));
        $qb->andWhere('oct.depo = :depo');
        $qb->setParameter('depo', $depot);
        $results = $qb->getQuery()->getResult();
        return $results;
    }

}