<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\SalesBundle\Entity\Order;

/**
 * OrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    public function orderAmountAdjust(Order $order)
    {
        $amount = $order->getPaidAmount();

        foreach($order->getOrderItems() as $orderItem){
            $dueAmount = $orderItem->getDueAmount();

            if($amount != 0 and $dueAmount != 0){
                if ($amount >= $dueAmount) {
                    $amount = $amount - $dueAmount;
                    $orderItem->setPaidAmount($dueAmount);
                } else{
                    $orderItem->setPaidAmount($amount);
                    $amount = 0;
                }
            }else{
                $orderItem->setPaidAmount(0);
            }
            $this->update($orderItem);
        }
    }

    public function getTotalOrderItemByOrder(Order $order)
    {
        $query = $this->createQueryBuilder('o');
        $query
            ->select('SUM(o.quantity) AS totalQuantity')
            ->where('o.order = :order')
            ->setParameter('order', $order);

        return $query->getQuery()->getSingleScalarResult();
    }

    public function orderItemReport($data)
    {
        $query = $this->createQueryBuilder('oi');
        $query->join('oi.order', 'o');
        $query->join('oi.item', 'i');
        $query->select('i.name as itemName');
        $query->addSelect('i.id as id');
        $query->addSelect('SUM(oi.quantity) as quantity');
        $query->addSelect('SUM(oi.totalAmount) as totalAmount');

        $this->handleSearchByItem($data, $query);
        $this->handleSearchByTwoDate($data, $query);

        $query->andWhere('o.orderState = :COMPLETE');
        $query->setParameter('COMPLETE', Order::ORDER_STATE_COMPLETE);

        $query->groupBy('i.id');
        $query->orderBy('i.name');

        $result = $query->getQuery()->getResult();

        $data = array();
        foreach($result as $row) {
            $data[$row['id']] = $row;
        }

        return $data;
    }

    protected function handleSearchByItem($data, $query)
    {
        if (!empty($data['search']['item'])) {
            $query->where('i.id = :item');
            $query->setParameter('item', $data['search']['item']);
        }
    }

    protected function handleSearchByTwoDate($data, $query)
    {
        if (!empty($data['start_date']) && !empty($data['end_date'])) {
            $query->andWhere('o.createdAt >= :start_date');
            $query->andWhere('o.createdAt <= :end_date');
            $query->setParameter('start_date', $data['start_date'].' 00:00:01');
            $query->setParameter('end_date', $data['end_date'].' 23:59:59');
        }
    }
}
