<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use DateTime;
use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\SalesBundle\Entity\OrderChickTemp;
use Rbs\Bundle\SalesBundle\Entity\OrderItemChickTemp;

/**
 * OrderItemChickTempRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemChickTempRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

}
