<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\SalesBundle\Entity\Sms;

/**
 * SmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmsRepository extends EntityRepository
{
    public function removeOrder(Sms $sms)
    {
        $sms->setOrder(null);
        $sms->setStatus('UNREAD');
        $this->_em->persist($sms);
        $this->_em->flush();
    }

    public function prepareXmlToObject($xml)
    {
        $sms = new Sms();
        $sms
            ->setSl($xml['SL'])
            ->setMobileNo($xml['MOBILENO'])
            ->setDate(new \DateTime($xml['INTIME']))
            ->setMsg($xml['MSG'])
            ->setStatus('NEW')
        ;

        $this->_em->persist($sms);
    }
}
