<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\CoreBundle\Entity\Warehouse;
use Rbs\Bundle\SalesBundle\Entity\Delivery;
use Rbs\Bundle\SalesBundle\Entity\DeliveryItem;
use Rbs\Bundle\SalesBundle\Entity\Order;
use Rbs\Bundle\SalesBundle\Entity\OrderItem;
use Rbs\Bundle\SalesBundle\Entity\Stock;
use Rbs\Bundle\SalesBundle\Entity\StockHistory;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Form;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    public function addStockToOnHold(Order $order, Warehouse $warehouse)
    {
        /** @var OrderItem $orderItem */
        foreach ($order->getOrderItems() as $orderItem) {
            /** @var Stock $stock */
            $stock = $this->findOneBy(
                array(
                    'item' => $orderItem->getItem()->getId(),
                    'warehouse' => $warehouse->getId(),
                )
            );
            $stock->setOnHold($stock->getOnHold() + $orderItem->getQuantity());
            $this->_em->persist($stock);
            $this->_em->flush();
        }
    }

    public function removeStockFromOnHold(Delivery $delivery)
    {
        /** @var DeliveryItem $deliveryItem */
        foreach ($delivery->getDeliveryItems() as $deliveryItem) {
            /** @var Stock $stock */
            $stock = $this->findOneBy(
                array(
                    'item' => $deliveryItem->getOrderItem()->getItem()->getId(),
                    'warehouse' => $delivery->getWarehouse()->getId(),
                )
            );
            $stockQty = $stock->getOnHold() - $deliveryItem->getQty();
            $stock->setOnHold($stockQty); // $stockQty > 0 ? $stockQty : 0
            $this->_em->persist($stock);
            $this->_em->flush();
        }
    }

    public function subtractFromOnHold(array $items)
    {
        foreach ($items as $itemId => $qty) {
            $stock = $this->findOneBy(array('item' => $itemId));
            $stock->setOnHold($stock->getOnHold() - $qty);
            $this->_em->persist($stock);
            $this->_em->flush();
        }
    }

    public function extractOrderItemQuantity(Order $order)
    {
        $data = array();
        /** @var OrderItem $orderItem */
        foreach ($order->getOrderItems() as $orderItem) {
            $data[$orderItem->getItem()->getId()] = $orderItem->getQuantity();
        }

        return $data;
    }

    public function save(Request $request,Form $form, StockHistory $stockHistory)
    {
        $stockRepo = $this->_em->getRepository('RbsSalesBundle:Stock');
        $stockID = (int)$request->request->all()['stock']['stockID'];
        $stock = $stockRepo->find($stockID);

        $quantity = $form->getData()->getQuantity();
        $quantity = $stock->getOnHand() + $quantity;

        $stock->setOnHand($quantity);
        $stockHistory->setStock($stock);

        $stockRepo->update($stock);
        $this->create($stockHistory);
    }

}