<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\CoreBundle\Entity\Depo;
use Rbs\Bundle\CoreBundle\Entity\Item;
use Rbs\Bundle\CoreBundle\Entity\ItemType;
use Rbs\Bundle\SalesBundle\Entity\Agent;
use Rbs\Bundle\SalesBundle\Entity\ChickenSetForAgent;
use Rbs\Bundle\SalesBundle\Entity\Delivery;
use Rbs\Bundle\SalesBundle\Entity\DeliveryItem;
use Rbs\Bundle\SalesBundle\Entity\Order;
use Rbs\Bundle\SalesBundle\Entity\OrderItem;
use Rbs\Bundle\SalesBundle\Entity\Stock;
use Rbs\Bundle\SalesBundle\Entity\StockHistory;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Form;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    public function addStockToOnHold(Order $order, Depo $depo)
    {
        /** @var OrderItem $orderItem */
        foreach ($order->getOrderItems() as $orderItem) {
            /** @var Stock $stock */
            $stock = $this->findOneBy(
                array(
                    'item' => $orderItem->getItem()->getId(),
                    'depo' => $depo->getId(),
                )
            );
            $stock->setOnHold($stock->getOnHold() + $orderItem->getQuantity());
            $this->_em->persist($stock);
            $this->_em->flush();
        }
    }

    public function removeStock(Delivery $delivery)
    {
        /** @var DeliveryItem $deliveryItem */
        foreach ($delivery->getDeliveryItems() as $deliveryItem) {
            /** @var Stock $stock */
            $stock = $this->findOneBy(
                array(
                    'item' => $deliveryItem->getOrderItem()->getItem()->getId(),
                    'depo' => $delivery->getDepo()->getId(),
                )
            );

            $stockOnHoldQty = $stock->getOnHold() - $deliveryItem->getQty();
            $stockOnHandQty = $stock->getOnHand() - $deliveryItem->getQty();

            $stock->setOnHold($stockOnHoldQty > 0 ? $stockOnHoldQty : 0); // $stockQty > 0 ? $stockQty : 0
            $stock->setOnHand($stockOnHandQty > 0 ? $stockOnHandQty : 0); // $stockQty > 0 ? $stockQty : 0

            $this->_em->persist($stock);
            $this->_em->flush();
        }
    }

    public function subtractFromOnHold(array $items)
    {
        foreach ($items as $itemId => $qty) {
            $stock = $this->findOneBy(array('item' => $itemId));
            $stock->setOnHold($stock->getOnHold() - $qty);
            $this->_em->persist($stock);
            $this->_em->flush();
        }
    }

    public function extractOrderItemQuantity(Order $order)
    {
        $data = array();
        /** @var OrderItem $orderItem */
        foreach ($order->getOrderItems() as $orderItem) {
            $data[$orderItem->getItem()->getId()] = $orderItem->getQuantity();
        }

        return $data;
    }

    public function save(Request $request,Form $form, StockHistory $stockHistory)
    {
        $stockRepo = $this->_em->getRepository('RbsSalesBundle:Stock');
        $stockID = (int)$request->request->all()['stock']['stockID'];
        $stock = $stockRepo->find($stockID);

        $quantity = $form->getData()->getQuantity();
        $quantity = $stock->getOnHand() + $quantity;

        $stock->setOnHand($quantity);
        $stockHistory->setStock($stock);
        $stockHistory->setFromDepo($stock->getDepo());

        $stockRepo->update($stock);
        $this->create($stockHistory);
    }

    // TODO: Need to implement on order approve 1st step
    public function hasStock(OrderItem $orderItem, Depo $depo, Agent $agent = null) {

        $item = $orderItem->getItem();

        if ($orderItem->getItem()->getItemType() == ItemType::Chick) {
            /** @var ChickenSetForAgent $chickenCheckForAgent */
            $chickenCheckForAgent = $this->_em->getRepository('RbsSalesBundle:ChickenSetForAgent')->findOneBy(array(
                'item' => $item->getId(), 'agent' => $agent->getId(),
            ));

            return array(
                'availableChick' => $chickenCheckForAgent ? $chickenCheckForAgent->isStockAvailable($orderItem->getQuantity()) : 0,
                'isAvailableQty' => $chickenCheckForAgent ? $chickenCheckForAgent->getQuantity() : false
            );
        }

        $stockItem = $this->findOneBy(
            array('item' => $orderItem->getItem()->getId(), 'depo' => $depo)
        );

        return $stockItem && $stockItem->isStockAvailable($orderItem->getQuantity());
    }

}