<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\SalesBundle\Entity\Order;
use Rbs\Bundle\SalesBundle\Entity\OrderItem;
use Rbs\Bundle\SalesBundle\Entity\Stock;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    public function addStockToOnHold(Order $order)
    {
        /** @var OrderItem $orderItem */
        foreach ($order->getOrderItems() as $orderItem) {
            /** @var Stock $stock */
            $stock = $this->findOneBy(array('item' => $orderItem->getItem()->getId()));
            $stock->setOnHold($stock->getOnHold() + $orderItem->getQuantity());
            $this->_em->persist($stock);
            $this->_em->flush();
        }
    }

    public function subtractFromOnHold(array $items)
    {
        foreach ($items as $itemId => $qty) {
            $stock = $this->findOneBy(array('item' => $itemId));
            $stock->setOnHold($stock->getOnHold() - $qty);
            $this->_em->persist($stock);
            $this->_em->flush();
        }
    }

    public function extractOrderItemQuantity(Order $order)
    {
        $data = array();
        /** @var OrderItem $orderItem */
        foreach ($order->getOrderItems() as $orderItem) {
            $data[$orderItem->getItem()->getId()] = $orderItem->getQuantity();
        }

        return $data;
    }
}
