<?php

namespace Rbs\Bundle\SalesBundle\Repository;

use DateTime;
use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\SalesBundle\Entity\Target;

/**
 * TargetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TargetRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        /** @var Target $target */
        foreach ($data->getChildEntities() as $target) {
            $target->setUser($data->getUser());
            if($target->getStartDate() == null or $target->getEndDate() == null){
                $target->setStartDate(null);
                $target->setEndDate(null);
            }else{
                $target->setStartDate($this->getDateObject("01-".$target->getStartDate()));
                $target->setEndDate($this->getDateObject($this->getDateWithLastDateOfMonth("01-".$target->getEndDate())));
            }
            $this->_em->persist($target);
        }
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    /**
     * @param $stringDate
     * @return String
     */
    protected function getDateWithLastDateOfMonth($stringDate)
    {
        $dateWithLastDateOfMonth = date('t-m-Y', strtotime($stringDate));
        return $dateWithLastDateOfMonth;
    }

    /**
     * @param $stringDate
     * @return DateTime
     */
    protected function getDateObject($stringDate)
    {
        $dateObject = new DateTime($stringDate);
        return $dateObject;
    }
}
