<?php

namespace Rbs\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BankAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankAccountRepository extends EntityRepository
{
    public function getAccountListWithBankBranch()
    {
        $qb = $this->createQueryBuilder('account')
            ->select("bank.name AS bankName, branch.name as branchName, account.id, account.name as accountName, account.code as accountCode")
            ->join('account.branch', 'branch')
            ->join('branch.bank', 'bank')
            ->addOrderBy('bank.name', 'asc')
            ->addOrderBy('branch.name', 'asc')
            ->getQuery()->getResult();

        $data = array();
        foreach ($qb as $row) {
            $data[$row['id']] = $row['accountCode'].' - '.$row['accountName'] . ' - ' . $row['bankName'] . ' - ' . $row['branchName'];
        }

        return $data;
    }
}
