<?php

namespace Rbs\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\CoreBundle\Entity\Bank;

/**
 * BankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankRepository extends EntityRepository
{

    public function getBankForApi()
    {
        $query = $this->createQueryBuilder('bank');
        $query->orderBy('bank.id', 'ASC');

        $results = $query->getQuery()->getResult();
        $returnArray=array();
        if($results){
            /* @var Bank $result*/
            foreach ($results as $result) {
                $returnArray[]=array(
                    'id'=>$result->getId(),
                    'name'=>$result->getName(),
                    'slug'=>$result->getSlug(),
                );
            }
        }
        return $returnArray;
    }
}
