<?php

namespace Rbs\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DepoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepoRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    public function getDepoId($user)
    {
        $query = $this->createQueryBuilder('d');
        $query->join('d.users', 'u');
        $query->select('d.id');
        $query->andWhere('u.id = :user');
        $query->setParameter('user', $user);

        return $query->getQuery()->getResult();
    }
}
