<?php

namespace Rbs\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\CoreBundle\Entity\SaleIncentive;

/**
 * SaleIncentiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleIncentiveRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }
    
    public function getAllMonthIncentiveByGroup()
    {
        $query = $this->createQueryBuilder('si');
        $query->where('si.deletedAt IS NULL');
        $query->andWhere('si.durationType = :month');
        $query->setParameter('month', SaleIncentive::MONTH);
        $query->groupBy('si.incentiveGroup');

        return $query->getQuery()->getResult();
    }

    public function getAllMonthIncentiveByYear()
    {
        $query = $this->createQueryBuilder('si');
        $query->where('si.deletedAt IS NULL');
        $query->andWhere('si.durationType = :year');
        $query->setParameter('year', SaleIncentive::YEAR);
        $query->groupBy('si.incentiveGroup');

        return $query->getQuery()->getResult();
    }
}
