<?php

namespace Rbs\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\CoreBundle\Entity\SaleIncentive;

/**
 * SaleIncentiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleIncentiveRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    public function getAllMonthGroupIncentive()
    {
        $query = $this->createQueryBuilder('si');
        $query->join('si.category', 'c');
        $query->distinct();
        $query->select('si.amount');
        $query->addSelect('si.quantity');
        $query->addSelect('si.group');
        $query->where('si.deletedAt IS NULL');
        $query->andWhere('si.durationType = :month');
        $query->setParameter('month', SaleIncentive::MONTH);

        return $query->getQuery()->getResult();
    }

    public function getAllYearGroupIncentive()
    {
        $query = $this->createQueryBuilder('si');
        $query->distinct();
        $query->select('si.amount');
        $query->addSelect('si.quantity');
        $query->addSelect('si.group');
        $query->where('si.deletedAt IS NULL');
        $query->andWhere('si.durationType = :year');
        $query->setParameter('year', SaleIncentive::YEAR);

        return $query->getQuery()->getResult();
    }
    
    public function getAllMonthIncentiveByMonthGroup()
    {
        $query = $this->createQueryBuilder('si');
        $query->join('si.category', 'c');
        $query->select('c.name');
        $query->addSelect('si.group');
        $query->where('si.deletedAt IS NULL');
        $query->andWhere('si.durationType = :month');
        $query->setParameter('month', SaleIncentive::MONTH);

        return $query->getQuery()->getResult();
    }

    public function getTotalMonthGroupName()
    {
        $query = $this->createQueryBuilder('si');
        $query->select('si.group');
        $query->where('si.deletedAt IS NULL');
        $query->andWhere('si.durationType = :month');
        $query->setParameter('month', SaleIncentive::MONTH);
        $query->groupBy('si.group');

        return $query->getQuery()->getScalarResult();
    }

    public function getAllYearIncentiveByMonthGroup()
    {
        $query = $this->createQueryBuilder('si');
        $query->join('si.category', 'c');
        $query->select('c.name');
        $query->addSelect('si.group');
        $query->where('si.deletedAt IS NULL');
        $query->andWhere('si.durationType = :YEAR');
        $query->setParameter('YEAR', SaleIncentive::YEAR);

        return $query->getQuery()->getResult();
    }

    public function getTotalYearGroupName()
    {
        $query = $this->createQueryBuilder('si');
        $query->select('si.group');
        $query->where('si.deletedAt IS NULL');
        $query->andWhere('si.durationType = :YEAR');
        $query->setParameter('YEAR', SaleIncentive::YEAR);
        $query->groupBy('si.group');

        return $query->getQuery()->getScalarResult();
    }

    public function getSalesIncentive($category, $quantity)
    {
        $query = $this->createQueryBuilder('si');
        $query->join('si.category', 'c');
        $query->select('si.amount');
        $query->addSelect('si.quantity');
        $query->addSelect('c.id as categoryId');
        $query->where('si.deletedAt IS NULL');
        $query->andWhere('c.id = :category');
        $query->andWhere('si.quantity > :quantity');
        $query->orderBy('si.quantity', 'ASC');
        $query->setMaxResults('1');
        $query->setParameters(array('category'=>$category, 'quantity'=>$quantity));

        return $query->getQuery()->getResult();
    }
}
