<?php

namespace Rbs\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TransportIncentiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportIncentiveRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    public function getAllTransportIncentive()
    {
        $query = $this->createQueryBuilder('ti');
        $query->join('ti.itemType', 'it');
        $query->join('ti.depo', 'd');
        $query->join('ti.district', 'dis');
        $query->join('ti.station', 'sta');
        $query->select('ti.amount');
        $query->addSelect('it.itemType');
        $query->addSelect('d.name as depo');
        $query->addSelect('dis.name as district');
        $query->addSelect('sta.name as station');
        $query->where('ti.deletedAt IS NULL');
        $query->orderBy('dis.name', 'ASC');

        return $query->getQuery()->getResult();
    }
}
