<?php

namespace Rbs\Bundle\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    public function users()
    {
        $query = $this->createQueryBuilder('u');
        $query->where('u.userType = :User OR u.userType = :Agent');
        $query->setParameter('User', 'User');
        $query->setParameter('Agent', 'Agent');

        return $query->getQuery()->getResult();
    }
}
