<?php

namespace Rbs\Bundle\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Rbs\Bundle\UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    public function users()
    {
        $query = $this->createQueryBuilder('u');
        $query->where('u.userType = :User OR u.userType = :Agent');
        $query->setParameter('User', 'User');
        $query->setParameter('Agent', 'Agent');

        return $query->getQuery()->getResult();
    }

    public function getRsmList()
    {
        $query = $this->createQueryBuilder('u');
        $query->where('u.userType = :RSM');
        $query->setParameter('RSM', User::RSM);

        return $query->getQuery()->getResult();
    }

    public function getSrList()
    {
        $query = $this->createQueryBuilder('u');
        $query->where('u.userType = :SR');
        $query->setParameter('SR', User::SR);

        return $query->getQuery()->getResult();
    }

    public function getNawParentId($locationId)
    {
        $query = $this->createQueryBuilder('u');
        $query->select('u.id');
        $query->where('u.userType = :RSM');
        $query->andWhere('u.location = :location');
        $query->setParameter('RSM', User::RSM);
        $query->setParameter('location', $locationId);

        return $query->getQuery()->getResult();
    }
}
